---
title: "06_06_2023_ExtractingData02"
output: pdf_document
date: "2023-06-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pdftools)
library(tesseract)
library(stringr)
library(rlist)
library(dplyr)
library(tidyverse)
library(schoolmath)
```

```{r}
#reading pdf
data <- pdf_data("./data/2021_PAM_600-3_ADA.pdf")
```

```{r}
# MOS

# extracting page 1
page1data <- data[[1]]

# making a character vector of all our words
page1textsep <- as.character(page1data$text)

# getting text of page 1
page1text <- paste(page1textsep, collapse = " ")

page1text
# getting MOS
MOS <- str_extract(page1text, pattern = "^.*?(?=\\h\\d)")
```

```{r}
# trying things on a small chunk of the pdf

# extracting page 4
page4data <- data[[4]]

# making a character vector of all our words
page4textsep <- as.character(page4data$text)

# getting the full text
page4text <- paste(page4textsep, collapse = " ")

# make a regex for stuff we want to extract
pattern1 <- "(\\h[a-z]\\.\\h).*?(?=\\h[a-z]\\.\\h)|(\\h[a-z]\\.\\h).*?(?=$)"

# make an example to test a regex on
example <- "text. e. some text here. f. some more text. g. final text"

# does it work? yep :)
str_extract_all(example, pattern1)

# try on page 4
str_extract_all(page4text, pattern = pattern1)
```


```{r}
# moving to larger chunks

# let's make a bigger string
pages4to7data <- list.rbind(data[4:7])
pages4to7sep <- as.character(pages4to7data$text)
fulltext <- paste(pages4to7sep, collapse = " ")

# try extraction...works :) 
sections <- str_extract_all(fulltext, pattern = pattern1)

# get it out of list
info <- unlist(sections[[1]])
```

```{r}
# extract rank

# create empty vector
ranks <- character()

# for loop to add rank to vector
for (i in info) {
  ranks <- str_extract(info, pattern = "(?<=\\h[a-z]\\.\\h).*?(?=\\h)")
}
```

```{r}
# start paring down to assignments

# empty character vector
assignmentparagraphs <- character()

#extract paragraphs
for(i in info) {
  assignmentparagraphs <- str_extract_all(info, pattern = "(\\(2\\).*(?=\\(3\\)))|(\\(3\\).*(?=\\(4\\)))")
}
paragraphs <- unlist(assignmentparagraphs)
paragraphs
```

```{r}
# make an empty data frame to store data

# variable name
columns <- c("MOS", "Rank", "Assignment", "Type", "Para")

# data frame
dataframe <- data.frame(matrix(nrow = 5, ncol = length(columns)))

# assigning column names
colnames(dataframe) <- columns
```

```{r}
# hard coding the lieutenant data

# grabbing dev. assignments
LTassignments <- unlist(str_extract_all(paragraphs[2], pattern = "(?<=include\\h).*?(?=\\,)|(?<=\\,\\h).*?(?=\\,)|(?<=and\\h).*?(?=\\.)"))

# cleaning up assignments
forward <- LTassignments[-1]

#input data
dataframe$MOS <- MOS
dataframe[c(1:5),2] <- ranks[1]
dataframe[1,3] <- "Platoon Leader"
dataframe[1,4] <- "KD"
dataframe[1,5] <- 1
dataframe[c(2:5),3] <- forward[1:4]
dataframe[c(2:5),4] <- "DEV"
dataframe[c(2:5),5] <- 2
```

```{r}
# let's work with the rest of our data

#wrangling
paragraphs2 <- paragraphs[3:10]
paragraphs3 <- paste(paragraphs2, collapse = " ")
paragraphs4 <- unlist(str_split(paragraphs3, "\\(\\d\\)"))
pasted <- paste(paragraphs4[6:12], collapse = " " )
finalparagraphs <- c(paragraphs4[1:5],paragraphs4[13:16])
finalparagraphs <- finalparagraphs[-1]
finalparagraphs
pastesection <- unlist(str_split(pasted, "\\.\\h"))
pastesection <- pastesection[-9]
```

```{r}
# making a function to return assignments

myfunction <- function(input){
  vector <- unlist(str_extract_all(input, pattern = "(?<=\\(.\\)\\h).*?(?=\\.)|(?<=\\(.\\)\\h).*?(?=\\h$)"))
  return(vector)
}
# apply!
mylist <- lapply(finalparagraphs,myfunction)

#clean it up
mylist[[4]] <- c(mylist[[4]], pastesection)


```

```{r}
# making paragraph assignments

# vector of paragraph numbers
vector <- seq(1:8)

# function for getting lengths of each assignment
myfunction2 <- function(input) {
  length1 <- length(input)
}

# got the lengths
output <- unlist(map(mylist, myfunction2))

# making our column
paranumbers <- rep(seq(vector[1:8]), output[1:8])

#working on adding in ranks
output2 <- c(output[1] + output[2], output[3] + output[4], output[5] + output[6], output[7] + output[8])

#making ranks numbers
ranksnumbers <- rep(seq(1:4), output2[1:4])
```

```{r}
# new data frame
columns <- c("MOS", "Rank", "Assignment", "Type", "Para")

# data frame
dataframe2 <- data.frame(matrix(nrow = 67, ncol = length(columns)))

# assigning column names
colnames(dataframe2) <- columns

# adding things in
dataframe2$MOS <- MOS
dataframe2$Assignment <- finallist
dataframe2$Para <- paranumbers

# adding in KD and Developing
dataframe2$Type <- ifelse(dataframe2$Para %% 2 == 0, "DEV", "KD")

# adding in ranks

dataframe2$Rank <- case_when(
  ranksnumbers == 1 ~ "CAP",
  ranksnumbers == 2 ~ "MAJ",
  ranksnumbers == 3 ~ "LTC",
  ranksnumbers == 4 ~ "COL"
                             )
```

```{r}
# joining datasets
joined <- rbind(dataframe, dataframe2)
fulldata <- joined[,-5]
```

