---
title: "08_06_2023Armor"
output: pdf_document
date: "2023-06-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pdftools)
library(tesseract)
library(stringr)
library(rlist)
library(dplyr)
library(tidyverse)
```

```{r}
# extracting data
data <- pdf_data("./data/armor-da-pam-600-3-a-2.pdf")

# establishing MOS
MOS <- "Armor"

# we want pages 3-9

pages3to9 <- list.rbind(data[3:9])
pages3to9sep <- as.character(pages3to9$text)
fulltext <- paste(pages3to9sep, collapse = " ")
```

```{r}
# find all of our KD paragraphs
KDs <- unlist(str_extract_all(fulltext, "(Key)(\\h)(developmental).*?(?=(\\h[a-z]\\.\\h)|(Examples))|(KD).*?(?=\\h[a-z]\\.\\h)"))

#get rid of a broadening that made its way in

KDs <- KDs[-4]
KDs

# find all of our broadening paragraphs

DEVs <- unlist(str_extract_all(fulltext, "([Bb]roadening)(\\h)([Aa]ssignments).*?(?=\\h[a-z]\\.\\h)"))

# clean
DEVs <- DEVs[-c(1,3,4)]
DEVs
```

```{r}
# make a dataframe to start storing

# variable name
columns <- c("MOS", "Rank", "Assignment", "Type", "Para")

# data frame
dataframe <- data.frame(matrix(nrow = 5, ncol = length(columns)))

# assigning column names
colnames(dataframe) <- columns

```


```{r}
# clean the KDs

# LT and CAP hard, might as well just hard code those in

dataframe$MOS <- MOS
dataframe[1,c(2,3,4)] <- c("LT", "Platoon Leader", "KD")
dataframe[2,c(2,3,4)] <- c("CAP", "Company/Troop Commander", "KD")
dataframe[3,c(2,3,4)] <- c("CAP", "Staff Officer", "KD")

# now that we've dealt with those...

KDsClean <- KDs[3:5]
KDassignments <- unlist(str_extract_all(KDsClean, "\\(\\d\\).*?(?=(\\(\\d\\))|(Note)|(There))"))
KDassignments
```

